source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "9.1"
inhibit_all_warnings!

def available_pods
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTCameraRoll',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod "react-native-linkedin-login", :path => "../node_modules/react-native-linkedin-login"

  # yoga is required for RN40 and above versions. If you don't include yoga then you will get
  # Error =>  Unable to satisfy the following requirements:
  #          'Yoga (= 0.42.0.React)' required by 'React/Core(0.42)'
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
end

target 'RNLinkedinLoginExample' do
  available_pods
end

target 'RNLinkedinLoginExampleTests' do
   available_pods
end
